from pydantic import BaseModel
from typing import Optional
from datetime import datetime

# Base schema shared between create and read
class BookBase(BaseModel):
    title: str
    author_id: Optional[int] = None
    publication_year: Optional[int] = None
    genre: Optional[str] = None


# Used for POST (create) requests
class BookCreate(BookBase):
    pass  # book_id is auto-generated by the DB


# Used for PUT (update) requests
class BookUpdate(BaseModel):
    title: Optional[str] = None
    author_id: Optional[int] = None
    publication_year: Optional[int] = None
    genre: Optional[str] = None


# Used for responses (GET requests)
class BookRead(BookBase):
    book_id: int
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    deleted_at: Optional[datetime] = None

    class Config:
        orm_mode = True
